---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Plotly

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

We are going to make interactive plots: 

Focus on AirBnB Dataset
```{r}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  select(
    borough = neighbourhood_group, 
    neighbourhood, stars, price, room_type, lat, long) %>% 
  drop_na(stars) %>% 
  filter(
    borough == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

Lets make a Scatter plot:

```{r}
nyc_airbnb %>% 
  mutate(text_label = str_c("Price: $", price, "/nRating: ", stars)) %>% 
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```

Lets make a Box Plot: 

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, 
          color = ~neighbourhood, 
          type = "box", 
          colors = "viridis")
```

Bar Charts -- less common but still helpful 

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>%
  plot_ly(x = ~neighbourhood, 
          y = ~n, 
          color = ~neighbourhood, 
          type = "bar", 
          colors = "viridis")
```

We should realistically never be using ggplotly 